language: csharp
solution: HashDepot.sln
install:
  - nuget restore HashDepot.sln
  - nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory bin
script:
  - xbuild /p:Configuration=Release HashDepot.sln
  - mono ./bin/NUnit.ConsoleRunner.3.2.0/tools/nunit3-console.exe ./test/bin/Release/HashDepot.Test.dll

